### ISSUE TITLE
i have problem when i login 

### ISSUE THREAD

**Issue by shadihh9** [dcodx/graphql-security-labs#1]
![grt](https://user-images.githubusercontent.com/22076930/91211312-3eacd680-e717-11ea-8b03-0b26ac383334.png)

**Comment by dcodx** [comment]
Hi @shadihh9  did you try the cred here:https://github.com/dcodx/graphql-security-labs/blob/master/lab5-injections/populate-database.py?

Let us know if you have any other issue
