### ISSUE TITLE
i have problem

### ISSUE THREAD

**Issue by shadihh9** [dcodx/graphql-security-labs#2]
hi i have problem when go to admin endpoints in graphql-injections when go to admin endpoints it logout and ask me username and pass

**Comment by dcodx** [comment]
Hello @shadihh9 

it is normal. You first need to login using a set of username and password that are stored in the DB. You can check the populate-database.py file to see all the credentials. 

For example you can use:

username: `johndoe`
password: `password1`

After that you should be able to login and see the app

**Comment by shadihh9** [comment]
and also have problem when i solve challange  grpahql injection
![i have problem](https://user-images.githubusercontent.com/22076930/92466536-e8d93380-f1d8-11ea-9726-92ddb34da09d.png)
 Background on this error at: http://sqlalche.me/e/13/e3q8

**Comment by shadihh9** [comment]
and also have problem when i solve challange  grpahql injection
![i have problem](https://user-images.githubusercontent.com/22076930/92466536-e8d93380-f1d8-11ea-9726-92ddb34da09d.png)
 Background on this error at: http://sqlalche.me/e/13/e3q8
