### ISSUE TITLE
have problem when i solve challange graphql injection

### ISSUE THREAD

**Issue by shadihh9** [dcodx/graphql-security-labs#3]
have problem when i solve challange graphql injection
![i have problem](https://user-images.githubusercontent.com/22076930/92469066-d7922600-f1dc-11ea-83da-d2275c21fd7f.png)

**Comment by shadihh9** [comment]
plz reply fast

**Comment by dcodx** [comment]
Hi @shadihh9 

this is normal behaviour when using the UNION keyword in SQL. You must have the same number of columns in the 2 queries that you are concatenating. 

Please follow the README to understand how to solve the lab. Everything is in there :)

**Comment by shadihh9** [comment]
thanks solve problem
